### PR TITLE
update videos

### PR DESCRIPTION
**Pull request by marcioc0sta**
@mergulhao #463

### CODE REVIEW

**Comment by mergulhao** [comment]
Check if you have how to remove this upper header of the video: http://cl.ly/image/170y103t0M3P

Like was done here in the Startupdev video: http://helabs.com/en/services/startupdev/

PS: the original branch for this fix is PR#463

**Comment by marcioc0sta** [comment]
I think that the startupdev video doesn't have the bar because it is an iframe and they accept the '&showinfo=0' parameter. I'll make some more attempts.

**Comment by marcioc0sta** [comment]
@mergulhao headers removed

**Comment by mergulhao** [comment]
Ok. Perfect. Now check if everything listed on #463 was done. Some of these new videos are still private on Youtube. They should be public, so check it too.

**Comment by marcioc0sta** [comment]
@mergulhao okay i'll check

**Comment by mergulhao** [comment]
@marcioc0sta How is it?

**Comment by marcioc0sta** [comment]
@mergulhao I'm having trouble finding the account HE on youtube. I'm having trouble finding the account HE on youtube. Using onelogin it directs me to youtube, but using my account and not the HE. I asked to @Analuvieira the account, while awaiting her answer i'll do other things

**Comment by mergulhao** [comment]
Probably @eduardofiorezi can give you access to Youtube. @Analuvieira is sick today.

**Comment by marcioc0sta** [comment]
@mergulhao New videos are public now. The next step is: Merge and remove older videos.

**Comment by mergulhao** [comment]
@marcioc0sta Ok. Are you going to finish everything today?

**Comment by marcioc0sta** [comment]
@mergulhao Yes! as soon as you do the merge, I will delete the old videos.

**Comment by mergulhao** [comment]
@marcioc0sta I'll not have time to do it today. Can you ask @obetomuniz for merge? Check if all the videos are the new ones.

**Comment by obetomuniz** [comment]
:+1:

**Pull request merged**
