### PR TITLE
Adding Olark Chat in StartupDev(MVP) Section

### PR DESCRIPTION
**Pull request by obetomuniz**

### CODE REVIEW

**Comment by obetomuniz** [comment]
@marcioj @mergulhao Can check this online for me? :smile: 

@RafaelEsberard Your request is finished, just need tests in production :+1:

**Comment by marcioj** [comment]
Does the chat got localized when switching between pt and en?

**Comment by obetomuniz** [comment]
@marcioj To customize I need to install first, then is that I can see if it is possible to change language.

**Comment by obetomuniz** [comment]
@marcioc0sta Yes, its possible: https://www.olark.com/using-olark/olark-in-your-favorite-language ... But we need to make it work in the first site.

**Pull request closed without merging**
