### PR TITLE
Update videos to new versions

### PR DESCRIPTION
**Pull request by mergulhao**
:warning: NOT READY TO MERGE YET :warning: 

 - [x] Add missed new video "Cultura da HE:labs" that was not uploaded yet (THE NEW VERSION). Ask @Analuvieira about it!
 - [x] Merge the branch
 - [x] Remove old videos from Youtube (DO NOT FORGET IT OR WE WILL END UP WITH DUP VIDEOS FOREVER AND OF COURSE WE DO NOT WANT IT!)

:warning: NOT READY TO MERGE YET :warning:

### CODE REVIEW

**Comment by Analuvieira** [comment]
Galera, eu vi agora o que aconteceu. Na verdade a bvaz (empresa que faz as traduçòes) ficou devendo essa da Cultura. Já mandei um email cobrando, eles devem me responder ainda hoje.
Depois disso eu subo lá lindão e aviso a todos..

**Comment by mikaelcarrara** [comment]
A Analu mandou o vídeo atualizado com a legenda: https://www.youtube.com/watch?v=4VJv9fujonc

**Comment by mergulhao** [comment]
@marcioc0sta can you update this PR with the new site organization? now we have all the updated videos.

**Comment by marcioc0sta** [comment]
@mergulhao yesterday i started this, but, it seems the Growth video has no EN captions:
https://www.youtube.com/watch?v=G0QLK5L7ETc

**Comment by mergulhao** [comment]
Ok. Move on anyway... I'll ask @Analuvieira to add EN captions.

**Comment by mergulhao** [comment]
@marcioc0sta missing feedback.

**Comment by marcioc0sta** [comment]
@mergulhao i talked to @Analuvieira on this morning and she told me that she will take care of it. When the video is ok i will do immediately the PR

**Comment by mergulhao** [comment]
Move on, even with no EN captions, ok?
Look: http://cl.ly/image/2F2b2A3q0W3Q

**Pull request closed without merging**
