### PR TITLE
Add accredify on works page

### PR DESCRIPTION
**Pull request by marcioc0sta**
@mergulhao to #473

### CODE REVIEW

**Comment by mergulhao** [comment]
@marcioc0sta these screenshots are **for sure** the interface we did, right?

**Comment by mergulhao** [comment]
@marcioc0sta As "we" understand HE:labs.

**Comment by marcioc0sta** [comment]
@mergulhao They are from https://www.accredify.com/#home

**Comment by mergulhao** [comment]
@marcioc0sta Check first if it was did by us... The client can already hired other company to continue the work... Got it?

**Comment by marcioc0sta** [comment]
@mergulhao Copy that! i'll check it

**Comment by marcioc0sta** [comment]
@mergulhao whole interface wasn't made for us, how to proceed?

**Comment by mergulhao** [comment]
@marcioc0sta Checkout the project from our repo. Run it. Make the screenshots.

**Comment by marcioc0sta** [comment]
@mergulhao  In our repository is already with the current interface, which was not made by us.

**Comment by mergulhao** [comment]
@marcioc0sta How is possible that in our repo have something that was no us that did? Is there someone else commiting there?

@eduardofiorezi can you help here?

**Comment by marcioc0sta** [comment]
@mergulhao maybe the interface of project does not belong to us, however as coded by us. I'm on a call with @eduardofiorezi now to resolve

**Comment by marcioc0sta** [comment]
@mergulhao Like what we did was just and backend API, i removed the screenshots of home and added the inside of the system and the api.

cc: @eduardofiorezi

**Comment by mergulhao** [comment]
@marcioc0sta Why is there a link in the bottom that links to the same page? Look: http://cl.ly/image/3U161v1k0t14

"See the full case."

**Comment by marcioc0sta** [comment]
@mergulhao Good catch! i was looking to other work pages and we have the same problem, i'll investigate this. Do updates here or open another PR for this problem?

**Comment by mergulhao** [comment]
@marcioc0sta Ok. Merging this one. You can open another one with the fix for this.

**Pull request merged**
