### PR TITLE
Add Thiago Belem to team

### PR DESCRIPTION
**Pull request by TiuTalk**

### CODE REVIEW

**Comment by marciovsena** [comment]
@TiuTalk, to keep the pattern you could replace the gravatar the image links by default image (160x160) and 2x (320x320)?

**Comment by TiuTalk** [comment]
I will update it tomorrow, thanks! :+1:

**Comment by TiuTalk** [comment]
@marciovsena done

**Comment by TiuTalk** [comment]
@marciovsena can you merge it?

**Comment by TiuTalk** [comment]
thanks @ndrluis

**Pull request merged**
